[docker_servers]
docker-server ansible_host=10.0.0.10 ansible_user=ec2-user

[ubuntu_servers]
jenkins-server ansible_host=10.0.0.11
k8s-server ansible_host=10.0.0.12

[ubuntu_servers:vars]
ansible_user=ubuntu

[all:vars]
ansible_become=true